DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS sauces;
CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL
);
CREATE TABLE sauces (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    heat TEXT NOT NULL
);